--- 
- name: Host configuration
  hosts: all
  user: ansible
  become: true
  roles:
    - common
    - orahost
- name: Oracle Database server installation & Database Creation 
  hosts: all
  user: ansible
  become: true 
  roles: 
    - oraswdb_install 
    - oradb_manage_db