--- 
- name: Host configuration
  hosts: all
  user: ansible
  sudo: yes
  roles:
    - common
    - orahost
- name: Oracle Database server installation & Database Creation 
  hosts: all
  user: ansible
  sudo: yes 
  sudo_user: oracle 
  roles: 
    - oraswdb_install 
    - oradb_manage_db